### PR TITLE
issue #87

### PR DESCRIPTION
**Pull request by alidevhere**
Hii @ezeoleaf  i would like to contribute to this issue. 
Thanks for your good work

### CODE REVIEW

**Review by ezeoleaf — APPROVED** [review]
⭐ Looks good to me

**Comment by ezeoleaf** [comment]
@alidevhere Thanks for your change and I think we can release it, but I would like to have a test for this new code :)

Can you add it?

**Comment by alidevhere** [comment]
Yeah sure!

**Comment by alidevhere** [comment]
@ezeoleaf 
i have added test case for change. 
Thanks.

**Pull request merged**
